dcos-tweeter/config/routes.rb
Rails.application.routes.draw do

  root 'tweets#index'

  resources :tweets, except: %w(edit new update)

  resources :analytics, except: %w(create edit new update show)
end

dcos-tweeter/app/models/analytics.rb
require 'cassandra'
require 'time'

# Tweet class that talks to Cassandra
class Analytics
  @@cluster = Cassandra.cluster(CASSANDRA_OPTIONS)
  @@keyspace = 'tweeter'
  @@session  = @@cluster.connect(@@keyspace)
  @@paging_state = nil

  attr_accessor :key, :frequency

  def self.all(paged = false)
    results = @@session.execute(
      'SELECT key, frequency FROM analytics ' \
      'WHERE kind = ? ORDER BY frequency DESC',
      arguments: ['tweet'],
      page_size: 25,
      paging_state: (paged ? @@paging_state : nil)
    )
    @@paging_state = results.paging_state
    results.map do |anal|
      c = Analytics.new
      c.key, c.frequency = anal['key'], anal['frequency']
      c
    end
  end
end

dcos-tweeter/app/models/tweet.rb
require 'cassandra'
require 'time'

# Tweet class that talks to Cassandra
class Tweet
  include ActiveModel::Serialization

  @@cluster = Cassandra.cluster(CASSANDRA_OPTIONS)
  @@keyspace = 'tweeter'
  @@session  = @@cluster.connect(@@keyspace)
  @@generator = Cassandra::Uuid::Generator.new
  @@paging_state = nil

  attr_accessor :id, :content, :created_at, :handle

  def avatar_url
    "//robohash.org/#{handle}.png?size=144x144&amp;bgset=bg2"
  end

  def attributes
    {'id' => id, 'content' => content, 'created_at' => created_at, 'handle' => handle}
  end

  def destroy
    @@session.execute(
      'DELETE from tweets WHERE id = ?',
      arguments: [@id])
  end

  def self.all(paged = false)
    result = @@session.execute(
      'SELECT id, content, created_at, handle FROM tweets ' \
      'WHERE kind = ? ORDER BY created_at DESC',
      arguments: ['tweet'],
      page_size: 25,
      paging_state: (paged ? @@paging_state : nil)
    )
    @@paging_state = result.paging_state
    result.map do |tweet|
      c = Tweet.new
      c.id, c.content, c.handle = tweet['id'], tweet['content'], tweet['handle']
      c.created_at = tweet['created_at'].to_time.utc.iso8601
      c
    end
  end

  def self.create(params)
    c = Tweet.new
    c.id = SecureRandom.urlsafe_base64
    c.content = params[:content]
    cassandra_time = @@generator.now
    c.created_at = cassandra_time.to_time.utc.iso8601
    c.handle = params[:handle].downcase
    @@session.execute(
      'INSERT INTO tweets (kind, id, content, created_at, handle) ' \
      'VALUES (?, ?, ?, ?, ?)',
      arguments: ['tweet', c.id, c.content, cassandra_time, c.handle])
    c
  end

  def self.find(id)
    tweet = @@session.execute(
      'SELECT id, content, created_at, handle FROM tweets WHERE id = ?',
      arguments: [id]).first
    c = Tweet.new
    c.id = tweet['id']
    c.content = tweet['content']
    c.created_at = tweet['created_at'].to_time.utc.iso8601
    c.handle = tweet['handle']
    c
  end
end

dcos-tweeter/app/controllers/analytics_controller.rb
# Analytics coontroller
class AnalyticsController < ActionController::Base
  layout 'application'

  def index
    @analytics = Analytics.all
  end
end

dcos-tweeter/app/controllers/application_controller.rb
# Main application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dcos-tweeter/app/controllers/tweets_controller.rb
# Tweets coontroller
class TweetsController < ActionController::Base
  layout 'application'

  def create
    @tweet = Tweet.create(tweet_params)
    log_tweet(@tweet)
    redirect_to root_path
  end

  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to root_path
  end

  def index
    @tweets = Tweet.all(params[:paged].present?)
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content, :handle)
  end

  def log_tweet(tweet)
    # TODO move producer setup out of request/response cycle
    kafka = Kafka.new(KAFKA_OPTIONS)
    producer = kafka.producer
    producer.produce(tweet.to_json, topic: KAFKA_TOPIC)
    producer.deliver_messages
  end
end

dcos-tweeter/app/views/analytics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="list-group">
        <% if @analytics.length < 1 %>
          <h3 class="text-muted text-center">
            You haven't done any analyzing, or you have no tweets to analyze!
          </h3>
        <% else %>
          <% @analytics.each do |anal| %>
            <div class="list-group-item">
              <span class="badge"><%= anal.frequency %></span>
              <h4><%= anal.key %></h4>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

dcos-tweeter/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Tweeter</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <a class="navbar-brand" href="/">
          Tweeter
        </a>
        <ul class="nav navbar-nav">
          <li><a href="/analytics" style="margin-top: 5px; margin-bottom: 5px; padding-top: 10px; padding-bottom: 6px;">Analytics</a></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

dcos-tweeter/app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= form_tag("/tweets", :method => "post") do |form| %>
            <div class="form-group">
              <%= label_tag "tweet[handle]", "Handle" %>
              <%= text_field_tag "tweet[handle]", nil,
                :autofocus => true,
                :class => "form-control",
                :maxlength => 15,
                :required => true,
                :pattern => "^[\\S]*$",
                :title => "Handles cannot contain spaces" %>
            </div>
            <div class="form-group">
              <%= label_tag "tweet[content]", "Compose new Tweet" %>
              <%= text_area_tag "tweet[content]", nil,
                :class => "form-control",
                :maxlength => 140,
                :required => true,
                :style => "resize: vertical;" %>
            </div>
            <div class="form-group clearfix">
              <%= submit_tag("Tweet", :class => "btn btn-primary btn-sm pull-right") %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="list-group">
        <% if @tweets.length < 1 %>
          <h3 class="text-muted text-center">
            What are you waiting for?<br>Start tweeting.
          </h3>
        <% else %>
          <% @tweets.each do |tweet| %>
            <div class="list-group-item">
              <div class="media">
                <div class="pull-left">
                  <img class="img-rounded media-object" src="<%= tweet.avatar_url %>"
                    width="48" height="48" alt="<%= tweet.handle %>">
                </div>
                <div class="media-body">
                  <h5 class="media-heading">
                    <div class="pull-right">
                      <%= form_tag(tweet_path(tweet.id), :method => "delete") do |form| %>
                        <%= hidden_field("tweet[id]", tweet.id) %>
                        <!-- <%= submit_tag("X", :class => "btn btn-link btn-xs text-muted", :title => "Delete tweet") %> -->
                      <% end %>
                    </div>
                    @<%= tweet.handle %> &middot;
                    <!-- <a href="<%= tweet_path(tweet.id) %>"> -->
                      <small>
                        <% created_at = tweet.created_at %>
                        <time datetime="<%= created_at %>">
                          <%= time_ago_in_words(DateTime.parse(created_at)) %>
                        </time>
                      </small>
                    <!-- </a> -->
                  </h5>
                  <%= simple_format tweet.content, :class => "tweet-content" %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

dcos-tweeter/app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="list-group">
          <div class="list-group-item">
            <div class="media">
              <div class="pull-left">
                <img class="img-rounded media-object" src="<%= @tweet.avatar_url %>"
                  width="48" height="48" alt="<%= @tweet.handle %>">
              </div>
              <div class="media-body">
                <h5 class="media-heading">
                  <div class="pull-right">
                    <%= form_tag(tweet_path(@tweet.id), :method => "delete") do |form| %>
                      <%= hidden_field("tweet[id]", @tweet.id) %>
                      <%= submit_tag("X", :class => "btn btn-link btn-xs text-muted", :title => "Delete tweet") %>
                    <% end %>
                  </div>
                  @<%= @tweet.handle %>
                </h5>
                <%= simple_format @tweet.content, :class => "tweet-content lead" %>
              </div>
              <hr>
              <div class="text-muted">
                <% created_at = @tweet.created_at %>
                <time datetime="<%= created_at %>">
                  <%= DateTime.parse(created_at).strftime("%H:%M UTC - %d %b %Y") %>
                </time>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>